### ISSUE TITLE
inconsistency with kubectl with invalid user

### ISSUE THREAD

**Issue by aviramha** [kube-rs/kube#1593] opened 2024-10-08 07:04 UTC
### Current and expected behavior

When using kube-rs over `kubectl proxy` kube-rs client doesn't work while kubectl does
```
kubectl config set-cluster testt --server=http://localhost:8001 --insecure-skip-tls-verify=true
kubectl config set-context testt --cluster=testt
kubectl config use-context testt
```
add in `~/.kube/config`

```yaml
users:
- name: testt
  user: 
    password: a
    username: a
```

and in the `testt context`:
```yaml
- context:
    cluster: testt
    user: testt
  name: testt
```

then run `kubectl get pods` (using kube-rs' kubectl example) and it will fail, while official binary works.

Found this while trying to work around https://github.com/metalbear-co/mirrord/issues/2803

### Environment

doesn't matter

### Affected crates

kube-client

### Would you like to work on fixing this bug?

No, since https://github.com/kube-rs/kube/issues/1594 is more important to me, but decided to log this issue for common knowledge.

**Comment by aviramha** [comment] 2024-10-08 07:06
https://github.com/kube-rs/kube/issues/1594

**Comment by clux** [comment] 2024-10-09 18:15
presumably duplicate of #1594 ?

**Comment by clux** [comment] 2024-10-09 18:16
looks like it, closing. please reopen if there's something missing

**Closed by clux** 2024-10-09 18:16 UTC
Labels: bug

**Comment by aviramha** [comment] 2024-10-09 18:18
Hey, it's not a duplicate - in this case it would still fail by supplying wrong auth while kubectl works somehow
